FROM alpine

RUN apk --update add tar curl bash g++ make

# Install Litmus

ADD https://s3.amazonaws.com/vtcsecure-github-distro/litmus-0.13.tar /tmp/litmus/litmus.tar

RUN tar -xvf /tmp/litmus/litmus.tar && \
    rm /tmp/litmus/litmus.tar && \
    mv litmus-0.13 litmus && \
    cd /litmus && \
    ./configure && \
    make install

# Test with something like: make URL=http://192.168.64.7/ CREDS="foo bar" check 
